### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by skypoint0** [MicrosoftDocs/Virtualization-Documentation.it-it#1]
Nella mia installazione sebbene la macchina virtuale (win XP) sia installata e funzionante NON appare la "finestra di connessione discreta che viene visualizzata quando ci si connette a una macchina virtuale" (sopra il primo screenshot). Potreste aiutarmi  a farla apparire (ho bisogno di condividere cartelle con l'host) ?
Grazie comunque per l'attenzione.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 202bcffa-b4da-e73b-4262-4bebdcaa794a
* Version Independent ID: 0f68d0a9-8618-178c-57d8-a86ada46de71
* Content: [Condividere i dispositivi con le macchine virtuali Windows](https://docs.microsoft.com/it-it/virtualization/hyper-v-on-windows/user-guide/enhanced-session-mode#feedback)
* Content Source: [virtualization/hyper-v-on-windows/user-guide/enhanced-session-mode.md](https://github.com/MicrosoftDocs/Virtualization-Documentation.it-it/blob/live/virtualization/hyper-v-on-windows/user-guide/enhanced-session-mode.md)
* Service: **windows-10-hyperv**
* Product: **windows-10-hyperv**
* GitHub Login: @olprod
* Microsoft Alias: **scooley**

**Comment by srvbpigh** [comment]
Hello, @skypoint0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Salve, @skypoint0 ,  

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione.  

Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS.  

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale.  

Il tuo contributo ai nostri articoli è molto apprezzato.   

Cordiali saluti,  

Il team internazionale Microsoft Docs
